import sqlite3

# Connect to SQLite database
conn = sqlite3.connect("flights_database.db")
cursor = conn.cursor()

# Create airlines table
cursor.execute("""
CREATE TABLE IF NOT EXISTS airlines (
    IATA_CODE TEXT PRIMARY KEY,
    AIRLINE TEXT
);
""")

# Create airports table
cursor.execute("""
CREATE TABLE IF NOT EXISTS airports (
    IATA_CODE TEXT PRIMARY KEY,
    AIRPORT TEXT,
    CITY TEXT,
    STATE TEXT,
    COUNTRY TEXT,
    LATITUDE REAL,
    LONGITUDE REAL
);
""")

# Create flights table
cursor.execute("""
CREATE TABLE IF NOT EXISTS flights (
    FLIGHT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    DAY_OF_WEEK INTEGER,
    AIRLINE TEXT,
    FLIGHT_NUMBER TEXT,
    TAIL_NUMBER TEXT,
    ORIGIN_AIRPORT TEXT,
    DESTINATION_AIRPORT TEXT,
    SCHEDULED_DEPARTURE INTEGER,
    DEPARTURE_TIME INTEGER,
    DEPARTURE_DELAY INTEGER,
    TAXI_OUT INTEGER,
    WHEELS_OFF INTEGER,
    SCHEDULED_TIME INTEGER,
    ELAPSED_TIME INTEGER,
    AIR_TIME INTEGER,
    DISTANCE INTEGER,
    WHEELS_ON INTEGER,
    TAXI_IN INTEGER,
    SCHEDULED_ARRIVAL INTEGER,
    ARRIVAL_TIME INTEGER,
    ARRIVAL_DELAY INTEGER,
    DIVERTED INTEGER,
    CANCELLED INTEGER,
    CANCELLATION_REASON TEXT,
    AIR_SYSTEM_DELAY INTEGER,
    SECURITY_DELAY INTEGER,
    AIRLINE_DELAY INTEGER,
    LATE_AIRCRAFT_DELAY INTEGER,
    WEATHER_DELAY INTEGER,
    FOREIGN KEY (AIRLINE) REFERENCES airlines(IATA_CODE),
    FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES airports(IATA_CODE),
    FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES airports(IATA_CODE)
);
""")

# Commit changes and close connection
conn.commit()
conn.close()
